[theme]
primaryColor = "#00A896"
backgroundColor = "#0B132B"
secondaryBackgroundColor = "#1C2541"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
